관통PJT/PJT05/MY_PJT05/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trends/', include('trends.urls')),
]

관통PJT/PJT05/MY_PJT05/trends/urls.py
from django.urls import path
from . import views


app_name = 'trends'

urlpatterns = [
    path('keyword/', views.keyword, name='keyword'),
    path('keyword/<int:pk>/', views.keyword_detail, name='keyword_detail'),
    path('crawling/', views.crawling, name='crawling'),
    path('crawling/histogram/', views.crawling_histogram, name='crawling_histogram'),
    path('crawling/advanced/', views.crawling_advanced, name='crawling_advanced'),
]

관통PJT/PJT05/MY_PJT05/trends/models.py
from django.db import models

# Create your models here.
class Keyword(models.Model):
    name = models.TextField()
    created_at = models.DateField(auto_now_add=False, auto_now=True)


class Trend(models.Model):
    name = models.TextField()
    result = models.IntegerField()
    search_period = models.TextField()
    created_at = models.DateTimeField(auto_now_add=False, auto_now=True)

관통PJT/PJT05/MY_PJT05/trends/forms.py
from django import forms
from .models import Keyword

class KeywordForm(forms.ModelForm):
    class Meta:
        model = Keyword
        fields = ['name']
        labels = {'name': '키워드:'}    # 'name' 필드의 레이블을 '키워드:'로 설정
        widgets = {
            'name': forms.TextInput(attrs={'style': 'width: 200px;'}) 
        }

관통PJT/PJT05/MY_PJT05/trends/views.py
from django.shortcuts import render,  redirect
from .models import Keyword, Trend
from .forms import KeywordForm

import re
from bs4 import BeautifulSoup
from selenium import webdriver

import matplotlib.pyplot as plt
import base64
from io import BytesIO

# Create your views here.

def keyword(request):
    if request.method == 'POST':
        form = KeywordForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('trends:keyword') 
    else:
        form = KeywordForm()  
    
    keywords = Keyword.objects.all()

    context = {
        'form': form,
        'keywords':keywords,
    }
    return render(request, 'trends/keyword.html', context)


def keyword_detail(request, pk):

    keyword = Keyword.objects.get(pk=pk)

    if request.method == 'POST':
        keyword.delete()
        trends = Trend.objects.filter(name = keyword.name)
        for trend in trends:
            trend.delete() 

        return redirect('trends:keyword')
    

    
def get_google_num(keyword, flag):
    # flag 값에 따라 검색 URL을 생성한다. 
    # flag가 0이면 검색 기간 제한이 없는 URL을 생성, 그 외의 경우는 1년 이내 결과를 가져올 URL을 생성한다.
    if flag == 0:
        url = f"https://www.google.com/search?q={keyword}"
    else:
        url = f"https://www.google.com/search?q={keyword}&tbs=qdr:y"

    # Selenium 웹 드라이버를 초기화하고 생성한 URL로 이동
    driver = webdriver.Chrome()
    driver.get(url)
     # 현재 웹 페이지의 HTML을 가져온다.
    html = driver.page_source
    # BeautifulSoup를 사용하여 HTML을 파싱하기
    soup = BeautifulSoup(html, "html.parser")

    # 검색 결과의 숫자를 포함하는 요소를 선택하는 과정.
    # 이 요소는 Google 검색 결과 페이지에서 결과 수를 나타내는 부분임.
    result_stats = soup.select_one("div#result-stats")

    # 검색 결과가 있는지 확인하고, 숫자 부분을 추출하여 반환한다.
    if result_stats:
        numeric_part = re.sub(r'\D', '', result_stats.text) # 숫자 이외의 문자를 제거하고 숫자 부분만 남긴다.
        return int(numeric_part) if numeric_part else -1    # 숫자로 변환하고 숫자가 없으면 -1을 반환.
    else:
        return -1       #  검색 결과가 없으면 -1을 반환.


def crawling(request):

    keywords = Keyword.objects.all()

    for keyword in keywords:
        # 해당 키워드로 Google에서 검색 결과의 숫자를 가져오기
        result_stats = get_google_num(keyword.name, 0)
         # 해당 키워드와 검색 기간이 'all'로 이미 데이터베이스에 있는지 확인하고, 없으면 생성하기
        try:
            trend, created = Trend.objects.get_or_create(name=keyword.name, search_period = "all")
        except:
            trend = Trend(name=keyword.name, search_period="all", result=-1)
        
        trend.result = result_stats
        trend.save()

    trends = Trend.objects.all()

    context = {
        'trends':trends,
    }
    return render(request, 'trends/crawling.html', context)


def crawling_histogram(request):

    trends = Trend.objects.all()

    x,y = [],[]
    for trend in trends:
        x.append(trend.name)
        y.append(trend.result)

    plt.clf()
    plt.figure(figsize=(12,6))
    plt.bar(x,y, label='Trends')
    plt.title('Technology Trend Analysis')
    plt.xlabel('Keyword')
    plt.ylabel('Result')
    plt.xticks(rotation=45)
    plt.legend()
    plt.grid(True)

    # 그래프를 이미지로 변환하고 base64로 인코딩하여 컨텍스트에 추가.
    buffer = BytesIO()
    plt.savefig(buffer, format='png')
    image_base64 = base64.b64encode(buffer.getvalue()).decode('utf-8').replace('\n', '')
    buffer.close()

    context = {
        'chart_image':f'data:image/png;base64,{image_base64}'
    }

    return render(request, 'trends/crawling_histogram.html', context)


def crawling_advanced(request):

    keywords = Keyword.objects.all()

    for keyword in keywords:
        result_stats = get_google_num(keyword.name , 1)
        try:
            trend, created = Trend.objects.get_or_create(name=keyword.name, search_period = "all")
        except:
            trend = Trend(name=keyword.name, search_period="all", result=-1)
        trend.result = result_stats
        trend.save()

    trends = Trend.objects.all()

    x,y = [],[]
    for trend in trends:
        x.append(trend.name)
        y.append(trend.result)

    plt.clf()
    plt.figure(figsize=(12,6))
    plt.bar(x,y, label='Trends')
    plt.title('Technology Trend Analysis')
    plt.xlabel('Keyword')
    plt.ylabel('Result')
    plt.xticks(rotation=45)
    plt.legend()
    plt.grid(True)

    buffer = BytesIO()
    plt.savefig(buffer, format='png')
    image_base64 = base64.b64encode(buffer.getvalue()).decode('utf-8').replace('\n', '')
    buffer.close()

    context = {
        'trends': trends,
        'chart_image':f'data:image/png;base64,{image_base64}'
    }

    return render(request, 'trends/crawling_advanced.html', context)

관통PJT/PJT05/MY_PJT05/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>트렌드 분석 애플리케이션</h1>
  <a href="{% url "trends:keyword" %}">키워드 추가</a>
  <a href="{% url "trends:crawling" %}">크롤링</a>
  <a href="{% url "trends:crawling_histogram" %}">히스토그램</a>
  <a href="{% url "trends:crawling_advanced" %}">지난 1년 크롤링</a>

  {% block content %}
  {% endblock content %}

</body>
</html>

관통PJT/PJT05/MY_PJT05/trends/templates/trends/crawling.html
{% extends "base.html" %}

{% block content %}
  <h2>크롤링 기초 - 전체 기간 검색 결과</h2>
  {% for trend in trends %}
    검색 결과 : {{ trend.name }} - {{ trend.result }}개 / 검색일자 : {{ trend.created_at|date:'y-m-d' }}
    <br>
    <hr>
  {% endfor %}
  
{% endblock content %}

관통PJT/PJT05/MY_PJT05/trends/templates/trends/crawling_advanced.html
{% extends "base.html" %}

{% block content %}
  <h2>전체 기간 검색 결과 히스토그램</h2>
  <img src="{{ chart_image }}" alt="">
{% endblock content %}

관통PJT/PJT05/MY_PJT05/trends/templates/trends/crawling_histogram.html
{% extends "base.html" %}

{% block content %}
  <h2>전체 기간 검색 결과 히스토그램</h2>
  <img src="{{ chart_image }}" alt="">
{% endblock content %}

관통PJT/PJT05/MY_PJT05/trends/templates/trends/keyword.html
{% extends "base.html" %}


{% block content %}
  <h2>키워드 추가</h2>
  <form action="{% url "trends:keyword" %}" method="POST">
    {% csrf_token %}
    {{ form.name.label_tag }}
    {{ form.name }}
    <input type="submit" value="생성하기">
  </form>
  <br>
  <hr>

  <h3>분석을 원하는 키워드 목록</h3>
  {% for keyword in keywords %}
    <p>{{keyword.pk}}번째 키워드 - {{keyword.name}}</p>
    <form action="{% url "trends:keyword_detail" keyword.pk %}" method='POST'>
      {% csrf_token %}
      <input type="submit" value = '삭제하기'>
    </form>
    <hr>
  {% endfor %}
{% endblock content %}