관통PJT/PJT06/MY_PJT06/accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/',views.signup, name='signup'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

관통PJT/PJT06/MY_PJT06/boards/urls.py
from django.urls import path
from . import views

app_name="boards"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'), 
    path('<int:pk>/update/', views.update, name='update'),   
    path('<int:board_pk>/comment/', views.comment, name='comment'),
    path('<int:board_pk>/comment/<int:comment_pk>/', views.comment_detail, name='comment_detail'),
    path("<int:board_pk>/likes/", views.likes, name="likes"),
]

관통PJT/PJT06/MY_PJT06/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('boards/', include('boards.urls')),
    path('accounts/', include('accounts.urls')),
]

관통PJT/PJT06/MY_PJT06/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')

관통PJT/PJT06/MY_PJT06/boards/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Board(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_boards')
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    board = models.ForeignKey(Board, on_delete=models.CASCADE, related_name='comments')
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

관통PJT/PJT06/MY_PJT06/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()

관통PJT/PJT06/MY_PJT06/boards/forms.py
from django import forms
from .models import Board, Comment

class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ('title', 'content', )

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )

관통PJT/PJT06/MY_PJT06/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserCreationForm
from django.contrib.auth import get_user_model
from django.views.decorators.http import require_POST, require_http_methods



# Create your views here.

@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('boards:index')
    
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('boards:index')
    else:
        form = AuthenticationForm()
    context = {
        'form' : form,
    }

    return render(request, 'accounts/login.html', context)


@require_POST
def logout(request):
    auth_logout(request)
    return redirect('boards:index')


@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('boards:index')
    
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user= form.save()
            auth_login(request, user)
            return redirect('boards:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form' : form,
    }
    return render(request, 'accounts/signup.html', context)



def profile(request, username):
    person = get_object_or_404(get_user_model(), username=username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)


@require_POST
def follow(request, user_pk):
    if request.user.is_authenticated:
        person = get_object_or_404(get_user_model(), pk=user_pk)
        if person != request.user:
            if person.followers.filter(pk=request.user.pk).exists():
                person.followers.remove(request.user)
            else:
                person.followers.add(request.user)
            return redirect('accounts:profile', person.username)
    return redirect('accounts:login')

관통PJT/PJT06/MY_PJT06/boards/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from .models import Board, Comment
from .forms import BoardForm, CommentForm
from django.views.decorators.http import require_http_methods, require_POST


# Create your views here.
@require_http_methods(["GET"])
def index(request):
    boards = Board.objects.all().order_by('-created_at')
    context = {
        'boards': boards
    }
    return render(request, 'boards/index.html', context)


@require_http_methods(["GET", "POST"])
def detail(request, pk):
    board = get_object_or_404(Board, pk=pk)
    if request.user == board.author:
        if request.method == 'POST':
            board.delete()
            return redirect('boards:index')
    comments = board.comments.all()
    comment_form = CommentForm()
    
    context = {
        'board': board,
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, 'boards/detail.html', context)


@require_http_methods(["GET", "POST"])
def update(request, pk):
    board = get_object_or_404(Board, pk=pk)

    if request.method == 'POST':
        form = BoardForm(request.POST, instance=board)
        if form.is_valid():
            form.save()
            return redirect('boards:detail', board.pk)
    else:
        form = BoardForm(instance=board)
    context = {
        'board': board,
        'form': form,
    }        
    return render(request, 'boards/update.html', context)


@require_http_methods(["GET", "POST"])
def create(request):
    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            board = form.save(commit=False)  
            board.author = request.user  
            board.save() 
            return redirect('boards:index')
    else:
        form = BoardForm()
    context = {
        'form': form,
    }
    return render(request, 'boards/create.html', context)


@require_http_methods(["POST"])
def comment(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.board = board
            comment.author = request.user
            comment.save()
            return redirect('boards:detail', board.pk)


@require_http_methods(["POST"])
def comment_detail(request, board_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.user == comment.author:
        if request.method == 'POST':
            comment.delete()
            return redirect('boards:detail', board_pk)
        

@require_POST
def likes(request, board_pk):
    if request.user.is_authenticated:
        board = get_object_or_404(Board, pk=board_pk)
        if board.like_users.filter(pk=request.user.pk).exists():
            board.like_users.remove(request.user)
        else:
            board.like_users.add(request.user)
        return redirect("boards:detail" , board_pk)
    return redirect("accounts:login")

관통PJT/PJT06/MY_PJT06/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
  <div>
    <h1 class="mb-4">로그인</h1>
    <form action="{% url "accounts:login" %} " method ='POST'>
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit" class="btn btn-light">Login</button>
    </form>
  </div>
{% endblock content %}

관통PJT/PJT06/MY_PJT06/accounts/templates/accounts/profile.html
{% extends "base.html" %}

{% block content %}
<div>

  <div style="display: flex; justify-content: space-between;">
    <h1 class="mb-4">{{person.username}}'s Profile Page</h1>
    <div style="display: flex; justify-content: space-between; align-items: center;">
      <p style="margin-right: 10px;">Followers: {{person.followers.count}} / Followings: {{person.followings.count}}</p> 
      {% if person != request.user %}
        <form action="{% url "accounts:follow" person.pk %}" method='POST'>
          {% csrf_token %}
          {% if request.user in person.followers.all %}
            <button type="submit" class="btn btn-primary">UnFollow</button>
          {% else %}
            <button type="submit" class="btn btn-primary">Follow</button>
          {% endif %}
        </form>
      {% endif %}
    </div>
  </div>

  <div>
    <p>회원번호 : {{person.pk}}</p>
    <p>유저이름 : {{person.username}}</p>
    <p>가입날짜 : {{person.date_joined}}</p>
  </div>

  <hr>
  <br>

  <h2 class="mb-4">Posts</h2><br>
    {% if person.board_set.all|length == 0 %} No posts yet.
    {% else %}
      {% for board in person.board_set.all %}
        <nav class="navbar navbar-expand-lg bg-light">
          <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <p class="nav-link">글번호 : {{board.pk}}</p>
                  <p class="nav-link">글제목 : <a href="{% url 'boards:detail' board.id %}" style="text-decoration: none;">{{ board.title }}</a></p>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <br>
      {% endfor %}
    {% endif %}
    
  <hr>
  <br>

  <h2 class="mb-4">Comments</h2><br>
    {% if person.comment_set.all|length == 0 %} No comments yet.
    {% else %}
      {% for comment in person.comment_set.all %}
        <nav class="navbar navbar-expand-lg bg-light">
          <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <p class="nav-link">글제목 : <a href="{% url 'boards:detail' comment.board.id %}" style="text-decoration: none;">{{ comment.board.title}}</a></p>
                  <p class="nav-link">댓글 : {{ comment.content }}</p>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <br>
      {% endfor %}
    {% endif %}
    
  <hr>
  <br>

  <h2 class="mb-4">Followers</h2><br>
    {% if person.followers.all|length == 0 %} No followers yet.
    {% else %}
      {% for follower in person.followers.all %}
        <nav class="navbar navbar-expand-lg bg-light">
          <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <p><a href="{% url "accounts:profile" follower.username %}" style="text-decoration: none;">{{follower.username}}</a></p>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      {% endfor %}
    {% endif %}

</div>
{% endblock content %}

관통PJT/PJT06/MY_PJT06/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
  <div></div>
    <h1 class="mb-4">회원가입</h1>
    <form action="{% url "accounts:signup" %} " method ='POST'>
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit" class="btn btn-light">SignUp</button>
    </form>
  </div>
{% endblock content %}

관통PJT/PJT06/MY_PJT06/boards/templates/boards/create.html
{% extends 'base.html' %}

{% block content %}
<div>
  <h1 class="mb-4">New Post</h1>
  <form action="{% url 'boards:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-light">Post</button>
  </form>
</div>
{% endblock content %}

관통PJT/PJT06/MY_PJT06/boards/templates/boards/detail.html
{% extends 'base.html' %}

{% block content %}
<div>

  <div class="d-flex justify-content-between">
    <h1 class="mb-4">Detail Page</h1>
  </div>

  <div>
    <p>글번호 : {{ board.id }}</p>  
    <p>글제목 : {{ board.title }}</p>
    <p>글내용 : {{ board.content }}</p>
    <p>작성날짜 : {{ board.created_at }}</p>
    <p>수정날짜 : {{ board.updated_at }}</p>
  </div>

  <hr>

  <div class="mb-5 d-flex justify-content-between ">
    <div>
      <form action="{% url 'boards:likes' board.pk %}" method="POST">
        {% csrf_token %}
        {% if request.user in board.like_users.all %}
          <button type="submit" class="btn btn-primary btn-sm">Like</button>
        {% else %}
          <button type="submit" class="btn btn-danger btn-sm">Like</button>
        {% endif %}
      </form>
      <p>Liked by {{ board.like_users.all|length }}.</p>
      <a href="{% url 'boards:index' %}"><button class="btn btn-light">Back Main Page</button></a>
    </div>
    <div class="d-flex">
      {% if request.user == board.author %}         
        <a href="{% url 'boards:update' board.id %}"><button class="me-3 btn btn-success">Update</button></a>
        <form action="{% url 'boards:detail' board.id%}" method='POST'>
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">Delete</button>
        </form>
      {% endif %}
    </div>
  </div> 


  <div>
    {% if request.user.is_authenticated %}
      <form action="{% url 'boards:comment' board.id %}" method='POST'>
        {% csrf_token %}
        <button class="btn btn-secondary" style="float: right;" type="submit">Add a comment</button>
        {{ comment_form.as_p }}
      </form>
    {% else %}
      <p><a href="{% url "accounts:login" %}" style="color: #FF8C00; text-decoration: none;">Pleae login in to write comments.</a></p>
    {% endif %}
  </div>

  <div>
    <div class="mt-5">
      {% if comments|length == 0 %}No Comments.
      {% else %}
        {% for comment in comments %}
          <hr>
          <div class="my-3 d-flex justify-content-between">
            <div>
              <span>{{comment.author}} - {{ comment.content }}</span>
              <span class="mx-5">({{ comment.created_at }})</span>
            </div>
            <div>
              {% comment %} 만약 게시글 작성자가 모든 댓글을 지울 수 있다면 ? or 이용하자. {% endcomment %}
              {% if request.user == comment.author or request.user == board.author %}
                <form action="{% url 'boards:comment_detail' board.id comment.id %}" method='POST'>
                  {% csrf_token %}
                  <button class="btn btn-light">Delete</button>
                </form>
              {% endif %}
            </div>
          </div>
        {% endfor %}
      {% endif %}
    </div>
  </div>

</div>
{% endblock content %}

관통PJT/PJT06/MY_PJT06/boards/templates/boards/index.html
{% extends 'base.html' %}

{% block content %}
<div>

  <div class="d-flex justify-content-between">
    <h1 class="mb-4">Main Page</h1>
    {% if request.user.is_authenticated %}
      <a style="height: 70%;" href="{% url 'boards:create' %}"><button class="btn btn-info">New Post</button></a>
    {% endif %}
  </div>

  <div>
    {% if boards|length == 0 %}No Posts.
    {% else %}
      {% for board in boards %}
        <p>글번호 : {{ board.id }}</p>  
        <p>작성자 : <a href="{% url "accounts:profile" board.author.username %}" style="text-decoration: none;">{{board.author.username}}</a></p>
        <p>글제목 : <a href="{% url 'boards:detail' board.id %}" style="text-decoration: none;">{{ board.title }}</a></p>
        <hr>
      {% endfor %}
    {% endif %}
  </div>

</div>
{% endblock content %}

관통PJT/PJT06/MY_PJT06/boards/templates/boards/update.html
{% extends 'base.html' %}

{% block content %}
<div>
  <h1 class="mb-4">수정 페이지</h1>
  <form action="{% url 'boards:update' board.id %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="수정하기">
  </form>
</div>
{% endblock content %}

관통PJT/PJT06/MY_PJT06/templates/_navbar.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'boards:index' %}">Main</a>
        </li>
        <li class="nav-item">
          {% if request.user.is_authenticated %}
            <a class="nav-link" aria-current="page" href="{% url 'accounts:profile' request.user %}">Profile</a>
          {% endif %}
        </li>
      </ul>
    </div>
  </div>
</nav>

관통PJT/PJT06/MY_PJT06/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <title>Document</title>
</head>
<body>

  <div class="mt-3 container">
    <div class="mt-3 mb-4 container">
      <div class="mb-3">
        <div class="d-flex justify-content-between">
          {% if request.user.is_authenticated %}
            <h2 class="mb-2">Hello, {{request.user.username}}!</h2>
              <form action="{% url "accounts:logout" %}" method='POST'>
                {% csrf_token %}
                <button type="submit" class="btn btn-light">Logout</button>
              </form>
          {% else %}
            <h2 class="mb-2">Please Login!</h2>
              <div>
                <a style="height: 50%;" href="{% url 'accounts:login' %}"><button type="button" class="btn btn-light">Login</button></a>
                <a style="height: 50%;" href="{% url 'accounts:signup' %}"><button type="button" class="btn btn-light">SignUp</button></a>           
              </div>
          {% endif %}
        </div>
      </div>
    </div>
    <hr>
  </div>

  <div class="mt-3 container">
    <div class="mt-3 mb-4">
      {% include '_navbar.html' %}
    </div>
    <div class="mb-5">
      {% block content %}
      {% endblock content %}
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>