관통PJT/PJT04/MY_PJT04/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('weathers/', include('weathers.urls'))
]

관통PJT/PJT04/MY_PJT04/weathers/urls.py
from django.urls import path
from . import views

app_name = 'weathers'

urlpatterns = [
    path('problem1/', views.problem1, name='problem1'),
    path('problem2/', views.problem2, name='problem2'),
    path('problem3/', views.problem3, name='problem3'),
    path('problem4/', views.problem4, name='problem4')
]

관통PJT/PJT04/MY_PJT04/weathers/views.py
import pandas as pd
import matplotlib.pyplot as plt
from django.shortcuts import render
from io import BytesIO
from mypjt.settings import BASE_DIR
import base64


def problem1(request):
    
    df = pd.read_csv(BASE_DIR/'austin_weather.csv')
    df_html = df.to_html(classes='table table-bordered table-striped')
    context = {
        'df_html' : df_html
    }
    return render(request, 'weathers/problem1.html', context)


def problem2(request):
    df = pd.read_csv(BASE_DIR/'austin_weather.csv')
    df['Date'] = pd.to_datetime(df['Date'])
    x = df['Date']
    y1 = df['TempHighF']
    y2 = df['TempAvgF']
    y3 = df['TempLowF']

    plt.clf()
    plt.figure(figsize=(12, 6))
    plt.plot(x, y1, label='High Temperature', color='blue')
    plt.plot(x, y2, label='Avg Temperature', color='orange')
    plt.plot(x, y3, label='Low Temperature', color='green')

    plt.title('Temperature Variation')
    plt.xlabel('Date')
    plt.ylabel('Temperature')
    plt.grid(True)
    plt.legend()

    buffer = BytesIO()
    plt.savefig(buffer, format='png')
    image_base64 = base64.b64encode(buffer.getvalue()).decode('utf-8').replace('\n', '')
    buffer.close()
    context = {
        'chart_image':f'data:image/png;base64,{image_base64}'
    }

    return render(request, 'weathers/problem2.html', context)


def problem3(request):
    df = pd.read_csv(BASE_DIR/'austin_weather.csv')
    df['Date'] = pd.to_datetime(df['Date'])
    df['TempHighF'] = pd.to_numeric(df['TempHighF'], errors='coerce')
    x = df.resample('M', on='Date')['Date'].max()
    y1 = df.resample('M', on='Date')['TempHighF'].mean()
    y2 = df.resample('M', on='Date')['TempAvgF'].mean()
    y3 = df.resample('M', on='Date')['TempLowF'].mean()

    plt.clf()
    plt.figure(figsize=(12, 6))
    plt.plot(x, y1, label='High Temperature', color='blue')
    plt.plot(x, y2, label='Avg Temperature', color='orange')
    plt.plot(x, y3, label='Low Temperature', color='green')

    plt.title('Temperature Variation')
    plt.xlabel('Date')
    plt.ylabel('Temperature')
    plt.grid(True)
    plt.legend()

    buffer = BytesIO()
    plt.savefig(buffer, format='png')
    image_base64 = base64.b64encode(buffer.getvalue()).decode('utf-8').replace('\n', '')
    buffer.close()
    context = {
        'chart_image':f'data:image/png;base64,{image_base64}'
    }

    return render(request, 'weathers/problem3.html', context)


def problem4(request):
    df = pd.read_csv(BASE_DIR/'austin_weather.csv')
    # df['Events'].fillna('No Events', inplace=True)

    counts = {}
    for event_list in df['Events']:
        events = event_list.split(',')
        for event in events:
            event = event.strip()
            counts[event] = counts.get(event, 0) + 1

    if '' in counts:
        counts['No Events'] = counts['']
        del counts['']

    sorted_events = sorted(counts.items(), key=lambda x: x[1], reverse=True)
    events, cnts = zip(*sorted_events)
    
 
    plt.clf()
    plt.figure(figsize=(12, 6))
    plt.bar(events,cnts)

    plt.title('Events Counts')
    plt.xlabel('Events')
    plt.ylabel('Count')
    plt.grid(True)

    buffer = BytesIO()
    plt.savefig(buffer, format='png')
    image_base64 = base64.b64encode(buffer.getvalue()).decode('utf-8').replace('\n', '')
    buffer.close()
    context = {
        'chart_image':f'data:image/png;base64,{image_base64}'
    }

    return render(request, 'weathers/problem4.html', context)

관통PJT/PJT04/MY_PJT04/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <a href="{% url "weathers:problem1" %}">문제1 |</a>
  <a href="{% url "weathers:problem2" %}">문제2 |</a>
  <a href="{% url "weathers:problem3" %}">문제3 |</a>
  <a href="{% url "weathers:problem4" %}">문제4 |</a>
  {% block content %}
  {% endblock content %}
</body>
</html>

관통PJT/PJT04/MY_PJT04/weathers/templates/weathers/problem1.html
{% extends "base.html" %}

{% block content %}
  <h1>문제1. 데이터 읽어오기</h1>
  {{ df_html | safe }}
{% endblock content %}

관통PJT/PJT04/MY_PJT04/weathers/templates/weathers/problem2.html
{% extends "base.html" %}

{% block content %}
  <h1>문제2. 일 별 온도 비교</h1>
  <img src="{{chart_image}}" alt="">
{% endblock content %}

관통PJT/PJT04/MY_PJT04/weathers/templates/weathers/problem3.html
{% extends "base.html" %}

{% block content %}
  <h1>문제3. 월 별 온도 비교</h1>
  <img src="{{chart_image}}" alt="">
{% endblock content %}

관통PJT/PJT04/MY_PJT04/weathers/templates/weathers/problem4.html
{% extends "base.html" %}

{% block content %}
  <h1>문제4. 날씨 이벤트</h1>
  <img src="{{chart_image}}" alt="">
{% endblock content %}